# Generated by Django 3.2.4 on 2021-07-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_order',
            old_name='Item_Id',
            new_name='Order_Id',
        ),
    ]
